
-- ==========================================
-- 3. NIVELES DE SUSCRIPCIÓN (57 registros reales)
-- ==========================================
PRINT 'Insertando niveles de suscripción...';

INSERT INTO NivelSuscripcion (idCreador, nombre, descripcion, precio_actual, esta_activo, orden) VALUES 
(1, 'Básico', 'Acceso a contenido general y publicaciones públicas.', 7.99, 1, 1),
(2, 'Básico', 'Acceso a contenido general y publicaciones públicas.', 7.99, 1, 1),
(2, 'Premium', 'Acceso a contenido exclusivo y descuentos.', 19.98, 1, 2),
(3, 'Básico', 'Acceso a contenido general y publicaciones públicas.', 7.99, 1, 1),
(3, 'Premium', 'Acceso a contenido exclusivo y descuentos.', 19.98, 1, 2),
(3, 'VIP', 'Acceso completo + contenido personalizado mensual.', 39.95, 1, 3),
(4, 'Básico', 'Acceso a contenido general y publicaciones públicas.', 7.99, 1, 1),
(4, 'Premium', 'Acceso a contenido exclusivo y descuentos.', 19.98, 1, 2),
(4, 'VIP', 'Acceso completo + contenido personalizado mensual.', 39.95, 1, 3),
(5, 'Básico', 'Acceso a contenido general y publicaciones públicas.', 7.99, 1, 1),
(6, 'Básico', 'Acceso a contenido general y publicaciones públicas.', 7.99, 1, 1),
(6, 'Premium', 'Acceso a contenido exclusivo y descuentos.', 19.98, 1, 2),
(7, 'Básico', 'Acceso a contenido general y publicaciones públicas.', 7.99, 1, 1),
(7, 'Premium', 'Acceso a contenido exclusivo y descuentos.', 19.98, 1, 2),
(7, 'VIP', 'Acceso completo + contenido personalizado mensual.', 39.95, 1, 3),
(8, 'Básico', 'Acceso a contenido general y publicaciones públicas.', 7.99, 1, 1),
(9, 'Básico', 'Acceso a contenido general y publicaciones públicas.', 7.99, 1, 1),
(9, 'Premium', 'Acceso a contenido exclusivo y descuentos.', 19.98, 1, 2),
(9, 'VIP', 'Acceso completo + contenido personalizado mensual.', 39.95, 1, 3),
(10, 'Básico', 'Acceso a contenido general y publicaciones públicas.', 7.99, 1, 1),
(11, 'Básico', 'Acceso a contenido general y publicaciones públicas.', 7.99, 1, 1),
(11, 'Premium', 'Acceso a contenido exclusivo y descuentos.', 19.98, 1, 2),
(11, 'VIP', 'Acceso completo + contenido personalizado mensual.', 39.95, 1, 3),
(12, 'Básico', 'Acceso a contenido general y publicaciones públicas.', 7.99, 1, 1),
(12, 'Premium', 'Acceso a contenido exclusivo y descuentos.', 19.98, 1, 2),
(12, 'VIP', 'Acceso completo + contenido personalizado mensual.', 39.95, 1, 3),
(13, 'Básico', 'Acceso a contenido general y publicaciones públicas.', 14.99, 1, 1),
(13, 'Premium', 'Acceso a contenido exclusivo y descuentos.', 37.48, 1, 2),
(13, 'VIP', 'Acceso completo + contenido personalizado mensual.', 74.95, 1, 3),
(14, 'Básico', 'Acceso a contenido general y publicaciones públicas.', 7.99, 1, 1),
(15, 'Básico', 'Acceso a contenido general y publicaciones públicas.', 7.99, 1, 1),
(15, 'Premium', 'Acceso a contenido exclusivo y descuentos.', 19.98, 1, 2),
(15, 'VIP', 'Acceso completo + contenido personalizado mensual.', 39.95, 1, 3),
(16, 'Básico', 'Acceso a contenido general y publicaciones públicas.', 7.99, 1, 1),
(16, 'Premium', 'Acceso a contenido exclusivo y descuentos.', 19.98, 1, 2),
(17, 'Básico', 'Acceso a contenido general y publicaciones públicas.', 7.99, 1, 1),
(17, 'Premium', 'Acceso a contenido exclusivo y descuentos.', 19.98, 1, 2),
(17, 'VIP', 'Acceso completo + contenido personalizado mensual.', 39.95, 1, 3),
(18, 'Básico', 'Acceso a contenido general y publicaciones públicas.', 7.99, 1, 1),
(18, 'Premium', 'Acceso a contenido exclusivo y descuentos.', 19.98, 1, 2),
(19, 'Básico', 'Acceso a contenido general y publicaciones públicas.', 7.99, 1, 1),
(19, 'Premium', 'Acceso a contenido exclusivo y descuentos.', 19.98, 1, 2),
(19, 'VIP', 'Acceso completo + contenido personalizado mensual.', 39.95, 1, 3),
(20, 'Básico', 'Acceso a contenido general y publicaciones públicas.', 7.99, 1, 1),
(20, 'Premium', 'Acceso a contenido exclusivo y descuentos.', 19.98, 1, 2),
(20, 'VIP', 'Acceso completo + contenido personalizado mensual.', 39.95, 1, 3),
(21, 'Básico', 'Acceso a contenido general y publicaciones públicas.', 7.99, 1, 1),
(21, 'Premium', 'Acceso a contenido exclusivo y descuentos.', 19.98, 1, 2),
(22, 'Básico', 'Acceso a contenido general y publicaciones públicas.', 7.99, 1, 1),
(22, 'Premium', 'Acceso a contenido exclusivo y descuentos.', 19.98, 1, 2),
(23, 'Básico', 'Acceso a contenido general y publicaciones públicas.', 7.99, 1, 1),
(23, 'Premium', 'Acceso a contenido exclusivo y descuentos.', 19.98, 1, 2),
(24, 'Básico', 'Acceso a contenido general y publicaciones públicas.', 7.99, 1, 1),
(24, 'Premium', 'Acceso a contenido exclusivo y descuentos.', 19.98, 1, 2),
(25, 'Básico', 'Acceso a contenido general y publicaciones públicas.', 7.99, 1, 1),
(25, 'Premium', 'Acceso a contenido exclusivo y descuentos.', 19.98, 1, 2),
(25, 'VIP', 'Acceso completo + contenido personalizado mensual.', 39.95, 1, 3),
(26, 'Básico', 'Acceso a contenido general y publicaciones públicas.', 14.99, 1, 1),
(26, 'Premium', 'Acceso a contenido exclusivo y descuentos.', 37.48, 1, 2);

PRINT '✅ 57 niveles de suscripción insertados';
GO
